import skinUrl from "@/shared/assets/models/skin.glb?url";
import myologyUrl from "@/shared/assets/models/myology.glb?url";
import heartUrl from "@/shared/assets/models/human_heart_3d_model.glb?url";
import lungsUrl from "@/shared/assets/models/realistic_human_lungs.glb?url";
import angiologyUrl from "@/shared/assets/models/angiology.glb?url";
import neurologyUrl from "@/shared/assets/models/neurology.glb?url";
import splanchnologyUrl from "@/shared/assets/models/splanchnology.glb?url";
import digestiveSystemUrl from "@/shared/assets/models/digestive_system.glb?url";
import liverUrl from "@/shared/assets/models/human_liver_and_gallbladder.glb?url";
import kidneyUrl from "@/shared/assets/models/human_kidney.glb?url";
import skullUrl from "@/shared/assets/models/skull.glb?url";
import orbitEyeUrl from "@/shared/assets/models/muscles_of_the_orbit_eye.glb?url";
import skeletonUrl from "@/shared/assets/models/skeleton.glb?url";
import diaphragmUrl from "@/shared/assets/models/human_diaphragm.glb?url";

export const MODEL_URLS = {
  skin: skinUrl,
  muscles: myologyUrl,
  myology: myologyUrl,
  heart: heartUrl,
  lungs: lungsUrl,
  angiology: angiologyUrl,
  circulatory: angiologyUrl,
  neurology: neurologyUrl,
  brain: neurologyUrl,
  splanchnology: splanchnologyUrl,
  digestive: digestiveSystemUrl,
  stomach: digestiveSystemUrl,
  intestines: digestiveSystemUrl,
  liver: liverUrl,
  kidneys: kidneyUrl,
  kidney: kidneyUrl,
  skull: skullUrl,
  eye: orbitEyeUrl,
  skeleton: skeletonUrl,
  diaphragm: diaphragmUrl,
};

export const SYSTEMS = {
  skin: { name: "Teri qoplami (Tana yuzasi)", short: "Teri", color: "#e8b89b", defaultVisible: true, defaultOpacity: 0.45 },
  organs: { name: "Ichki a'zolar (Splanxnologiya)", short: "A'zolar", color: "#f43f5e", defaultVisible: true, defaultOpacity: 1.0 },
  skeleton: { name: "Skelet (206 ta suyak)", short: "Skelet", color: "#f1f5f9", defaultVisible: true, defaultOpacity: 1.0 },
  vessels: { name: "Qon-tomir tizimi (Angiologiya)", short: "Qon-tomir", color: "#3b82f6", defaultVisible: true, defaultOpacity: 0.95 },
  muscles: { name: "Mushaklar tizimi (Miologiya)", short: "Mushaklar", color: "#dc2626", defaultVisible: true, defaultOpacity: 0.9 },
};

export const BODY_LAYERS = [
  { id: "skin", name: "Teri qoplami", short: "Teri", icon: "🧍", url: skinUrl, color: "#e8b89b", defaultOpacity: 0.45, explodeX: -2.0 },
  { id: "organs", name: "Ichki a'zolar", short: "A'zolar", icon: "🫁", url: splanchnologyUrl, color: "#f43f5e", defaultOpacity: 1.0, explodeX: -1.0 },
  { id: "skeleton", name: "Skelet (Suyaklar)", short: "Skelet", icon: "💀", url: skeletonUrl, color: "#f1f5f9", defaultOpacity: 1.0, explodeX: 0 },
  { id: "vessels", name: "Qon-tomir tizimi", short: "Qon-tomir", icon: "🩸", url: angiologyUrl, color: "#3b82f6", defaultOpacity: 0.95, explodeX: 1.0 },
  { id: "muscles", name: "Mushaklar tizimi", short: "Mushaklar", icon: "💪", url: myologyUrl, color: "#dc2626", defaultOpacity: 0.9, explodeX: 2.0 },
];

export const THREE_STAGES = [
  {
    id: "stage_assembled",
    time: 0,
    explode: 0.0,
    badge: "00:00",
    label: "To'liq tana (Yig'ilgan)",
    desc: "Barcha 5 ta anatomik tizim bitta yaxlit inson qiyofasida birlashgan.",
    cameraDistance: 4.8,
  },
  {
    id: "stage_peeling",
    time: 6,
    explode: 0.35,
    badge: "00:06",
    label: "Mushaklar va Teri ajralishi",
    desc: "Tashqi teri va mushak tolalari alohida qatlam sifatida ochiladi.",
    cameraDistance: 5.6,
  },
  {
    id: "stage_exploded",
    time: 14,
    explode: 1.0,
    badge: "00:14",
    label: "Portlatilgan atlas (5 ta tizim)",
    desc: "Teri, Ichki a'zolar, Skelet, Qon tomirlar va Mushaklar to'liq yonma-yon.",
    cameraDistance: 7.6,
  },
  {
    id: "stage_focus_skeleton",
    time: 21,
    explode: 0.75,
    badge: "00:21",
    label: "Skelet va Ichki a'zolar",
    desc: "206 suyakli tayanch karkasi va hayotiy muhim ichki a'zolar markazda.",
    cameraDistance: 6.2,
  },
  {
    id: "stage_reassembly",
    time: 28,
    explode: 0.1,
    badge: "00:28",
    label: "Qayta yig'ilish",
    desc: "Barcha qismlar qaytadan o'zaro birlashib yaxlit tanaga aylanadi.",
    cameraDistance: 5.0,
  },
];

export const BODY_PRESETS = [
  {
    id: "exploded",
    name: "💥 Portlatilgan (5 Tizim)",
    explode: 1.0,
    layers: { skin: 1.0, organs: 1.0, skeleton: 1.0, vessels: 1.0, muscles: 1.0 },
    opacities: { skin: 0.9, organs: 1.0, skeleton: 1.0, vessels: 0.95, muscles: 0.95 },
  },
  {
    id: "assembled",
    name: "🧍 Yaxlit Inson (Hammasi)",
    explode: 0.0,
    layers: { skin: 0.35, organs: 1.0, skeleton: 1.0, vessels: 0.95, muscles: 0.9 },
    opacities: { skin: 0.35, organs: 1.0, skeleton: 1.0, vessels: 0.95, muscles: 0.9 },
  },
  {
    id: "skeleton_only",
    name: "💀 Skelet (206 suyak)",
    explode: 0.0,
    layers: { skin: 0, organs: 0, skeleton: 1.0, vessels: 0, muscles: 0 },
    opacities: { skin: 0, organs: 0, skeleton: 1.0, vessels: 0, muscles: 0 },
  },
  {
    id: "muscles_only",
    name: "💪 Mushaklar anatomiyasi",
    explode: 0.0,
    layers: { skin: 0, organs: 0, skeleton: 0, vessels: 0, muscles: 1.0 },
    opacities: { skin: 0, organs: 0, skeleton: 0, vessels: 0, muscles: 1.0 },
  },
  {
    id: "viscera_vessels",
    name: "🫀 A'zolar va Qon aylanishi",
    explode: 0.5,
    layers: { skin: 0, organs: 1.0, skeleton: 0.3, vessels: 1.0, muscles: 0 },
    opacities: { skin: 0, organs: 1.0, skeleton: 0.3, vessels: 1.0, muscles: 0 },
  },
];

export const ORGAN_INFO = {
  heart: {
    name: "Yurak (3D Animatsiyali)",
    shortName: "Yurak",
    system: "Qon-tomir tizimi",
    color: "#e11d48",
    url: heartUrl,
    hasAnimation: true,
    animatedType: "heartbeat",
    desc: "To'rt kamerali kuchli mushak nasosi. Kislorodga to'yingan qonni butun tanaga haydab, metabolizm chiqindilari va karbonat angidridni qaytarib tozalashga yo'naltiradi.",
    summary: "To'rt kamerali kuchli mushak nasosi bo'lib, butun tana bo'ylab uzluksiz qon aylanishini ta'minlaydi.",
    fact: "Inson yuragi bir kunda o'rtacha 100 000 marta, bir yilda 36 million marta uradi. Hayot davomida 2.5 milliarddan ortiq qisqaradi.",
    funFact: "Inson yuragi bir kunda o'rtacha 100 000 marta uradi va 7 500 litrdan ortiq qon haydaydi.",
  },
  lungs: {
    name: "O'pka va Nafas yo'llari",
    shortName: "O'pka",
    system: "Nafas olish tizimi",
    color: "#f43f5e",
    url: lungsUrl,
    hasAnimation: true,
    animatedType: "breathing",
    desc: "Nafas olish tizimining markaziy juft a'zosi. Havodagi kislorodni qonga o'tkazib, qondagi karbonat angidrid gazini tashqariga chiqarish vazifasini bajaradi.",
    summary: "Havodan kislorodni qonga o'tkazuvchi va karbonat angidridni chiqaruvchi asosiy nafas a'zosi.",
    fact: "O'pka alveolalarining umumiy maydoni taxminan 70-100 kvadrat metrni tashkil qiladi - bu tennis korti o'lchamiga teng.",
    funFact: "O'pka alveolalari maydoni 70-100 kv. metrni tashkil qiladi va inson kuniga 11 000 litr havo bilan nafas oladi.",
  },
  brain: {
    name: "Bosh miya va Asab tizimi",
    shortName: "Bosh miya",
    system: "Asab tizimi",
    color: "#a855f7",
    url: neurologyUrl,
    desc: "Tananing oliy boshqaruv va axborot markazi. Sezgi, fikrlash, ixtiyoriy va avtomatik tana harakatlari hamda barcha hayotiy a'zolar faoliyatini muvofiqlashtiradi.",
    summary: "Barcha sezgi, harakat, xotira va hayotiy jarayonlarni muvofiqlashtiruvchi markaziy a'zo.",
    fact: "Bosh miyada taxminan 86 milliard neyron mavjud bo'lib, u tananing umumiy energiyasining 20% ini iste'mol qiladi.",
    funFact: "Bosh miyada 86 milliard neyron bor va u tanadagi umumiy energiyaning 20 foizini iste'mol qiladi.",
  },
  liver: {
    name: "Jigar va O't pufagi",
    shortName: "Jigar",
    system: "Hazm qilish tizimi",
    color: "#b91c1c",
    url: liverUrl,
    desc: "Organizmning eng katta kimyoviy laboratoriyasi. Oziq moddalarni qayta ishlaydi, qonni toksinlardan tozalaydi, yog'larni parchalash uchun o't suyuqligi (safro) ishlab chiqaradi.",
    summary: "Toksinlarni tozalovchi, o't suyuqligi ishlab chiqaruvchi va moddalar almashinuvini boshqaruvchi a'zo.",
    fact: "Jigar o'z to'qimasining 75% qismi olib tashlansa ham bir necha oy ichida dastlabki hajmiga to'liq qayta o'sib yetisha oladi.",
    funFact: "Jigar hatto 75% qismi zararlanganda ham butunlay qayta o'sib tiklana oladigan yagona ichki a'zodir.",
  },
  stomach: {
    name: "Oshqozon va Hazm yo'llari",
    shortName: "Oshqozon",
    system: "Hazm qilish tizimi",
    color: "#ea580c",
    url: digestiveSystemUrl,
    desc: "Qizilo'ngach, oshqozon, ingichka va yo'g'on ichaklardan iborat yaxlit ovqat hazm qilish tizimi. Ozuqa moddalarini parchalaydi va qonga so'radi.",
    summary: "Ovqatni kislota va fermentlar yordamida hazm qiluvchi va oziq moddalarni so'ruvchi tizim.",
    fact: "Oshqozon shirasi tarkibidagi xlorid kislotasi shu darajada kuchliki, oshqozon o'z-o'zini hazm qilib yubormasligi uchun har 3-4 kunda ichki shilliq qavatini yangilab turadi.",
    funFact: "Oshqozon shillig'i kislotadan himoyalanish uchun har bir necha kunda butunlay yangilanadi.",
  },
  kidneys: {
    name: "Buyraklar va Ayirish a'zolari",
    shortName: "Buyraklar",
    system: "Ayirish tizimi",
    color: "#be123c",
    url: kidneyUrl,
    desc: "Loviya shaklidagi juft a'zo. Qonni uzluksiz filtrlaydi, toksinlar va ortiqcha suyuqlikni siydik orqali chiqaradi, arterial qon bosimini nazorat qiladi.",
    summary: "Qonni tinimsiz tozalovchi va tana suyuqliklari muvozanatini saqlovchi filtrlash a'zosi.",
    fact: "Har bir buyrakda taxminan 1 millionta mikroskopik nefronlar joylashgan bo'lib, ular kuniga 180 litr qon plazmasini filtrlaydi.",
    funFact: "Har bir buyrakda 1 milliondan ortiq nefron mavjud bo'lib, ular kuniga 180 litr qonni filtrlaydi.",
  },
  intestines: {
    name: "Ingichka va Yo'g'on ichak",
    shortName: "Ichaklar",
    system: "Hazm qilish tizimi",
    color: "#d97706",
    url: digestiveSystemUrl,
    desc: "Ingichka ichak aminokislotalar, glyukoza va yog'larni so'radi; yo'g'on ichak esa suvni qayta shimib najas hosil qiladi.",
    summary: "Oziq moddalar va suvning so'rilishini amalga oshiruvchi ichak trakti.",
    fact: "Katta yoshli odamning ingichka ichagi uzunligi taxminan 6 metr, yo'g'on ichagi esa 1.5 metrga yetadi.",
    funFact: "Inson ingichka ichagining umumiy ichki yuzasi mikrovorsinkalar tufayli 30 kvadrat metrga yetadi.",
  },
  skeleton: {
    name: "To'liq Inson Skeleti (206 suyak)",
    shortName: "Skelet",
    system: "Tayanch-harakat tizimi",
    color: "#e2e8f0",
    url: skeletonUrl,
    desc: "206 ta suyakdan iborat anatomik tayanch karkasi. Miya, yurak, o'pkani himoyalaydi, mushaklar birikadigan richaglarni hosil qiladi va ilikda qon hujayralarini yaratadi.",
    summary: "Tananing 206 ta suyakdan iborat mustahkam tayanch va himoya tizimi.",
    fact: "Inson son suyagi (femur) tanadagi eng uzun va eng baquvvat suyak bo'lib, beton kabi katta yuklanishga bardosh beradi.",
    funFact: "Son suyagi inson tanasidagi eng baquvvat suyak bo'lib, 1 tonnagacha bo'lgan og'irlikni ko'tara oladi.",
  },
  muscles: {
    name: "To'liq Mushaklar tizimi (Miologiya)",
    shortName: "Mushaklar",
    system: "Tayanch-harakat tizimi",
    color: "#dc2626",
    url: myologyUrl,
    desc: "600 dan ortiq skelet mushaklaridan iborat majmua. Qisqarish orqali barcha tana harakatlarini ta'minlaydi, qomatni saqlaydi va issiqlik ishlab chiqaradi.",
    summary: "Tananing harakati, qomati va tana harorati barqarorligini ta'minlovchi mushaklar.",
    fact: "Chaynov mushagi (masseter) tana yuzasi nisbatida eng kuchli mushak hisoblanib, jag'da 90 kg dan ortiq bosim kuchi hosil qila oladi.",
    funFact: "Chaynov mushagi 90 kg dan ortiq bosim kuchi hosil qila oladigan tanadagi eng kuchli mushakdir.",
  },
  circulatory: {
    name: "Qon-tomir tizimi (Angiologiya)",
    shortName: "Qon-tomir",
    system: "Qon-tomir tizimi",
    color: "#3b82f6",
    url: angiologyUrl,
    desc: "Arteriyalar, venalar va kapillyarlardan iborat yaxlit transport tarmog'i. Kislorod, ozuqa, gormon va immunitet hujayralarini butun tanaga yetkazadi.",
    summary: "Arteriyalar, venalar va kapillyarlardan iborat butun tana qon transport tizimi.",
    fact: "Odam tanasidagi barcha qon tomirlarining umumiy uzunligi taxminan 100 000 km bo'lib, Yer ekvatorini 2.5 marta aylanishga yetadi.",
    funFact: "Barcha qon tomirlarining umumiy uzunligi 100 000 km bo'lib, Yer ekvatorini 2.5 marta o'rashga yetadi.",
  },
  skull: {
    name: "Bosh suyagi (Kalla anatomiyasi)",
    shortName: "Bosh suyagi",
    system: "Skelet tizimi",
    color: "#cbd5e1",
    url: skullUrl,
    desc: "Miya qutisi va yuz skeletini tashkil etuvchi 22 ta suyak birikmasi. Bosh miya va sezgi a'zolarini mustahkam himoya qiladi.",
    summary: "Bosh miya va yuz tuzilmalarini himoya qiluvchi mustahkam suyak majmuasi.",
    fact: "Kalla suyagida pastki jag'dan tashqari barcha suyaklar harakatsiz choklar orqali mahkam birlashgan.",
    funFact: "Kalla suyagining pastki jag'dan boshqa barcha suyaklari qo'zg'almas choklar bilan birlashgan.",
  },
  eye: {
    name: "Ko'z va Ko'z kosasi mushaklari",
    shortName: "Ko'z mushaklari",
    system: "Sezgi a'zolari",
    color: "#06b6d4",
    url: orbitEyeUrl,
    desc: "Ko'z soqqasi va uni turli yo'nalishlarda chaqqon harakatlantiruvchi 6 ta asosiy ko'z mushagi (to'g'ri va qiyshiq mushaklar).",
    summary: "Ko'rish a'zosi va uning 6 ta nozik harakatlanuvchi mushak apparati.",
    fact: "Ko'z mushaklari inson tanasidagi eng chaqqon mushaklar bo'lib, bir kunda 100 000 dan ortiq mikrog'imirlash harakatlarini bajaradi.",
    funFact: "Ko'z mushaklari tanadagi eng tezkor mushaklar bo'lib, soniyaning 1/100 qismida harakatlana oladi.",
  },
  diaphragm: {
    name: "Diafragma mushagi",
    shortName: "Diafragma",
    system: "Nafas olish tizimi",
    color: "#fb7185",
    url: diaphragmUrl,
    desc: "Ko'krak va qorin bo'shlig'i chegarasidagi gumbazsimon asosiy nafas mushagi. Har bir nafasda pastga tushib o'pka hajmini kengaytiradi.",
    summary: "Nafas olishning asosiy harakatlantiruvchi gumbazsimon mushagi.",
    fact: "Diafragma asabining (n. phrenicus) qisqa tutqanoqsimon qo'zg'alishi natijasida hammamizga tanish bo'lgan hiqichoq (singultus) paydo bo'ladi.",
    funFact: "Diafragmaning kutilmagan qisqarishi natijasida insonlarda hiqichoq yuzaga keladi.",
  },
};

export const DEFAULT_VISIBILITY = {
  skin: true,
  muscles: true,
  organs: true,
  vessels: true,
};

export const DEFAULT_SKIN_OPACITY = 0.35;
export const defaultLayerOpacity = (system) => {
  if (system === "skin") return DEFAULT_SKIN_OPACITY;
  if (system === "muscles") return 0.9;
  if (system === "vessels") return 0.95;
  return 1.0;
};

export const ANATOMY_CATEGORIES = [
  { id: "all", label: "Barchasi" },
  { id: "systems", label: "Asosiy Tizimlar" },
  { id: "organs", label: "Ichki A'zolar" },
];
export const SKETCHFAB_CATEGORIES = ANATOMY_CATEGORIES;

export const ANATOMY_TOPICS = [
  {
    id: "all",
    title: "To'liq Inson (Kesish & Qatlamlar)",
    short: "To'liq Tana",
    latin: "Corpus humanum",
    category: "all",
    icon: "User",
    keywords: [],
    color: "#10b981",
    desc: "Inson tanasining barcha 5 ta asosiy anatomik qatlami: 206 suyakli skelet, hayotiy ichki a'zolar, qon-tomir daraxti, 600+ mushak va tashqi teri yaxlit ko'rinishda. Slayder yordamida suyakdan terigacha (0-100%) ochish va istalgan o'qda kesib (slice) ichini ko'rish mumkin.",
    funFact: "Inson tanasi 30 trilliondan ortiq tirik hujayradan tashkil topgan bo'lib, har bir tizim tananing ichki muvozanatini saqlash uchun uyg'un harakat qiladi.",
    stats: [
      { label: "Asosiy qatlamlar", value: "5 ta yaxlit tizim" },
      { label: "Anatomik tuzilmalar", value: "23 ta asosiy a'zo" },
      { label: "Kesish imkoniyati", value: "3D Slicing Plane" },
    ],
  },
  {
    id: "skeleton",
    title: "Skelet tizimi (206 suyak)",
    short: "Skelet",
    latin: "Systema skeletale",
    category: "systems",
    icon: "Bone",
    keywords: ["skull", "spine", "ribcage", "pelvis", "hands", "legs"],
    color: "#f1f5f9",
    desc: "Inson skeleti 206 ta suyakdan iborat bo'lib, tanaga mustahkam tayanch beradi, miya va ichki a'zolarni zarbalardan himoya qiladi hamda mushaklar bilan birgalikda harakatni ta'minlaydi. Suyak ko'migida har soniyada millionlab yangi qon hujayralari ishlab chiqariladi.",
    funFact: "Inson tanasidagi eng uzun va baquvvat suyak son suyagi (femur) bo'lib, 1 tonnagacha bo'lgan og'irlik bosimiga bardosh bera oladi.",
    stats: [
      { label: "Suyaklar soni", value: "206 ta" },
      { label: "Asosiy vazifasi", value: "Tayanch va himoya" },
      { label: "Kalsiy zaxirasi", value: "99%" },
    ],
  },
  {
    id: "muscles",
    title: "Mushaklar tizimi (Miologiya)",
    short: "Mushaklar",
    latin: "Systema musculare",
    category: "systems",
    icon: "Dumbbell",
    keywords: ["musclespart"],
    color: "#ef4444",
    desc: "Inson tanasida 600 dan ortiq skelet mushaklari mavjud. Ular qisqarish va bo'shashish xususiyatiga ega bo'lib, qon aylanishi, nafas olish, qomatni tik tutish va barcha erkin harakatlarni amalga oshiradi.",
    funFact: "Inson tanasidagi nisbatan eng baquvvat mushak chaynov mushagi (masseter) bo'lib, jag'da 90 kg dan ortiq bosim hosil qila oladi.",
    stats: [
      { label: "Mushaklar soni", value: "600+ ta" },
      { label: "Tana vaznidagi ulushi", value: "40-50%" },
      { label: "Eng chaqqon mushak", value: "Ko'z mushagi" },
    ],
  },
  {
    id: "circulatory",
    title: "Qon-tomir tizimi (Angiologiya)",
    short: "Qon-tomir",
    latin: "Systema cardiovasculare",
    category: "systems",
    icon: "HeartPulse",
    keywords: ["arterias", "venas", "heart"],
    color: "#3b82f6",
    desc: "Yurak, arteriyalar, venalar va mayda kapillyarlardan tashkil topgan ulkan transport tizimi. Qon orqali tanadagi har bir hujayraga kislorod, ozuqa, gormonlar yetkaziladi va metabolizm chiqindilari chiqariladi.",
    funFact: "Odam tanasidagi barcha qon tomirlarining umumiy uzunligi taxminan 100 000 km bo'lib, bu Yer sharini 2.5 marta aylantirib o'rashga yetadi.",
    stats: [
      { label: "Tomirlar uzunligi", value: "100 000 km" },
      { label: "Qon hajmi", value: "4.5 - 5.5 litr" },
      { label: "To'liq aylanish vaqti", value: "20-25 soniya" },
    ],
  },
  {
    id: "organs",
    title: "Ichki a'zolar majmuasi",
    short: "Ichki a'zolar",
    latin: "Splanchnologia",
    category: "systems",
    icon: "Layers",
    keywords: ["humanlung", "digestive", "liver", "gallbladder", "urinary", "diafrag", "brain", "eye", "eyelash", "heart"],
    color: "#f59e0b",
    desc: "Hayotiy faoliyatni ta'minlovchi barcha asosiy ichki a'zolar: bosh miya, o'pka, yurak, jigar, oshqozon, ichaklar, buyraklar va diafragma yaxlit tarzda o'rganiladi.",
    funFact: "Ichki a'zolarimiz har lahzada doimiy o'zaro gormonal va asabiy aloqada bo'lib, tananing ichki muvozanatini (gomeostaz) saqlaydi.",
    stats: [
      { label: "Asosiy tizimlar", value: "Nafas, Hazm, Asab, Ayirish" },
      { label: "Boshqaruv", value: "Avtonom asab tizimi" },
      { label: "Ishlash tartibi", value: "24/7 uzluksiz" },
    ],
  },
  {
    id: "skin",
    title: "Teri qoplami (Yaxlit inson)",
    short: "Teri va Qomat",
    latin: "Integumentum commune",
    category: "systems",
    icon: "User",
    keywords: ["humanskin", "shorts"],
    color: "#f97316",
    desc: "Teri - inson tanasining eng katta organi. U ichki to'qimalarni mikroblar, ultrabinafsha nurlar va mexanik shikastlanishdan asraydi, tana haroratini boshqaradi va sezgi retseptorlari bilan ta'minlaydi.",
    funFact: "Katta odam terisining umumiy maydoni qariyb 2 kvadrat metrni tashkil qiladi va tana umumiy vaznining 16% ini tashkil qiladi.",
    stats: [
      { label: "Umumiy maydoni", value: "1.8 - 2.0 m²" },
      { label: "Og'irligi", value: "3 - 4 kg" },
      { label: "Qatlamlari", value: "Epidermis, derma, gipoderma" },
    ],
  },
  {
    id: "heart",
    title: "Yurak (Animatsiyali 3D)",
    short: "Yurak",
    latin: "Cor",
    category: "organs",
    icon: "Heart",
    keywords: ["heart"],
    color: "#e11d48",
    desc: "Yurak - qon aylanish tizimining markaziy mushak nasosi. U to'rt kameradan (ikkita bo'lmacha va ikkita qorincha) iborat bo'lib, daqiqada 60-80 marta ritmik qisqarib butun organizmni qon bilan ta'minlaydi.",
    funFact: "Inson yuragi bir kunda o'rtacha 100 000 marta urib, 7 500 litrdan ortiq qon haydaydi. Hayot davomida 2.5 milliarddan ortiq qisqaradi.",
    stats: [
      { label: "Zarb chastotasi", value: "60 - 80 zarb/daq" },
      { label: "Kunlik qon hajmi", value: "7 500+ litr" },
      { label: "Kameralar", value: "4 ta (2 bo'lmacha, 2 qorincha)" },
    ],
  },
  {
    id: "lungs",
    title: "O'pka va Nafas yo'llari",
    short: "O'pka",
    latin: "Pulmones",
    category: "organs",
    icon: "Wind",
    keywords: ["humanlung"],
    color: "#ec4899",
    desc: "Nafas olish tizimining markaziy juft a'zosi. Havodagi kislorodni qonga o'tkazadi va qondan karbonat angidridni chiqaradi. Bronx daraxti millionlab mayda pufakchalar - alveolalarga bo'linadi.",
    funFact: "O'pka alveolalarining umumiy maydoni taxminan 70-100 kvadrat metr bo'lib, bu butun boshli tennis korti maydoniga tengdir.",
    stats: [
      { label: "Alveolalar maydoni", value: "70 - 100 m²" },
      { label: "Kunlik havo", value: "11 000 litr" },
      { label: "Nafas soni", value: "16-20 marta/daq" },
    ],
  },
  {
    id: "brain",
    title: "Bosh miya va Asab markazi",
    short: "Bosh miya",
    latin: "Encephalon",
    category: "organs",
    icon: "Brain",
    keywords: ["brain"],
    color: "#8b5cf6",
    desc: "Tananing boshqaruv markazi va fikrlash organi. Bosh miya 86 milliard neyrondan iborat bo'lib, barcha sezgilarni tahlil qiladi, ixtiyoriy harakatlarni yo'naltiradi va ichki a'zolar ishini boshqaradi.",
    funFact: "Bosh miya tana umumiy vaznining atigi 2% ini tashkil qilsa-da, organizmdagi umumiy energiya va kislorodning 20% dan ortig'ini iste'mol qiladi.",
    stats: [
      { label: "Neyronlar soni", value: "86 milliard" },
      { label: "Energiya iste'moli", value: "20%" },
      { label: "O'rtacha vazni", value: "1.3 - 1.4 kg" },
    ],
  },
  {
    id: "liver",
    title: "Jigar va O't pufagi",
    short: "Jigar",
    latin: "Hepar & Vesica biliaris",
    category: "organs",
    icon: "Activity",
    keywords: ["liver", "gallbladder"],
    color: "#b91c1c",
    desc: "Organizmning eng katta ichki bezi va kimyoviy laboratoriyasi. Qonni toksinlardan tozalaydi, yog'larni hazm qilish uchun o't suyuqligi (safro) ishlab chiqaradi, glyukoza va vitaminlarni saqlaydi.",
    funFact: "Jigar hatto to'qimasining 75 foizi shikastlangan yoki olib tashlangan taqdirda ham o'z-o'zini bir necha oyda to'liq qayta tiklay oladigan yagona ichki organdir.",
    stats: [
      { label: "Vazni", value: "1.5 kg" },
      { label: "Funksiyalari", value: "500 dan ortiq" },
      { label: "Qon filtrlash", value: "1.4 litr/daq" },
    ],
  },
  {
    id: "digestive",
    title: "Oshqozon va Hazm tizimi",
    short: "Hazm yo'llari",
    latin: "Systema digestorium",
    category: "organs",
    icon: "UtensilsCrossed",
    keywords: ["digestive"],
    color: "#d97706",
    desc: "Qizilo'ngach, oshqozon va ichaklardan iborat yaxlit oshqozon-ichak trakti. Oziq-ovqatlarni mexanik va kimyoviy parchalab, tanaga zarur aminokislota, vitamin va minerallarni qonga so'radi.",
    funFact: "Oshqozon shirasidagi xlorid kislotasi shu qadar faolki, oshqozon o'zini-o'zi eritib yubormasligi uchun o'zining ichki shilliq qavatini har 3-4 kunda to'liq yangilab turadi.",
    stats: [
      { label: "Ingichka ichak", value: "5 - 6 metr" },
      { label: "Yo'g'on ichak", value: "1.5 metr" },
      { label: "So'rilish maydoni", value: "30 m²" },
    ],
  },
  {
    id: "kidneys",
    title: "Buyraklar va Ayirish a'zolari",
    short: "Buyraklar",
    latin: "Systema urinarium",
    category: "organs",
    icon: "Droplets",
    keywords: ["urinary"],
    color: "#0284c7",
    desc: "Loviya shaklidagi juft ayirish a'zosi. Har kuni qonni tinimsiz filtrlab, zaharli moddalar va ortiqcha suvni siydik orqali chiqaradi, qon bosimini va tuz-suv muvozanatini barqaror ushlaydi.",
    funFact: "Har bir buyrakda 1 milliondan ortiq mikroskopik nefronlar joylashgan bo'lib, ular bir kecha-kunduzda 180 litrgacha qonni filtrdan o'tkazadi.",
    stats: [
      { label: "Nefronlar soni", value: "2 millionta" },
      { label: "Kunlik filtrlash", value: "180 litr qon" },
      { label: "Hosil bo'ladigan siydik", value: "1.5 - 2 litr" },
    ],
  },
  {
    id: "diaphragm",
    title: "Diafragma nafas mushagi",
    short: "Diafragma",
    latin: "Diaphragma",
    category: "organs",
    icon: "Flame",
    keywords: ["diafrag"],
    color: "#f43f5e",
    desc: "Ko'krak qafasi bilan qorin bo'shlig'ini ajratib turuvchi gumbazsimon asosiy nafas mushagi. Har bir nafas olishda pastga tushib o'pkaga havo kirishini ta'minlaydi.",
    funFact: "Diafragma asabining kutilmagan qisqa tutqanoqsimon qo'zg'alishi natijasida hammamizga ma'lum bo'lgan hiqichoq hodisasi yuzaga keladi.",
    stats: [
      { label: "Mushak turi", value: "Gumbazsimon skelet mushagi" },
      { label: "Nafasdagi hissasi", value: "Nafas hajmining 75% i" },
      { label: "Asab bilan ta'minlanishi", value: "Nervus phrenicus" },
    ],
  },
  {
    id: "eyes",
    title: "Ko'zlar va Ko'z kosasi",
    short: "Ko'zlar",
    latin: "Organum visus",
    category: "organs",
    icon: "Eye",
    keywords: ["eye", "eyelash"],
    color: "#06b6d4",
    desc: "Ko'rish a'zosi va uni harakatlantiruvchi maxsus mushaklar kompleksi. Tashqi olamdagi barcha axborotning 80% dan ortig'i aynan ko'rish apparati orqali miyaga uzatiladi.",
    funFact: "Ko'z mushaklari inson tanasidagi eng chaqqon va charchamaydigan mushaklar bo'lib, kuniga 100 000 dan ortiq harakatlarni bajaradi.",
    stats: [
      { label: "Axborot ulushi", value: "80%+" },
      { label: "Harakatlantiruvchi mushaklar", value: "6 ta" },
      { label: "Ko'z chaqnash tezligi", value: "100 millisoniya" },
    ],
  },
];

export const getAnatomyTopic = (id) =>
  ANATOMY_TOPICS.find((t) => t.id === id) || ANATOMY_TOPICS[0];

export const getSketchfabTopic = getAnatomyTopic;
export const SKETCHFAB_TOPICS = ANATOMY_TOPICS;

export const DISCLAIMER = "AnatomiX 3D — Next-Gen Interaktiv Odam Anatomiyasi & Ilmiy Simulyatori ta'limiy va ilmiy maqsadlar uchun ishlab chiqilgan.";


